import { MedicineData } from '../types';

export const exportToMarkdown = (data: MedicineData) => {
  const md = `# ${data.summary.genericName}
**Brands:** ${data.summary.brandNames.join(', ')}
**Class:** ${data.summary.drugClass}
**Mechanism:** ${data.summary.mechanism}

## Educational Summary
**Patient:** 
${data.educational.patient}

**Medical Student:** 
${data.educational.student}

**Doctor:** 
${data.educational.doctor}

**Researcher:** 
${data.educational.researcher}

## Risk Classifications
- **Liver Toxicity:** ${data.riskClassifications.liverToxicity.level} (Confidence: ${data.riskClassifications.liverToxicity.confidence}%)\n  *Reasoning:* ${data.riskClassifications.liverToxicity.reasoning}
- **Kidney Toxicity:** ${data.riskClassifications.kidneyToxicity.level} (Confidence: ${data.riskClassifications.kidneyToxicity.confidence}%)\n  *Reasoning:* ${data.riskClassifications.kidneyToxicity.reasoning}
- **Cardiac Risk:** ${data.riskClassifications.cardiacRisk.level} (Confidence: ${data.riskClassifications.cardiacRisk.confidence}%)\n  *Reasoning:* ${data.riskClassifications.cardiacRisk.reasoning}
- **Pregnancy Risk:** ${data.riskClassifications.pregnancyRisk.level} (Confidence: ${data.riskClassifications.pregnancyRisk.confidence}%)\n  *Reasoning:* ${data.riskClassifications.pregnancyRisk.reasoning}
- **Addiction Potential:** ${data.riskClassifications.addictionPotential.level} (Confidence: ${data.riskClassifications.addictionPotential.confidence}%)\n  *Reasoning:* ${data.riskClassifications.addictionPotential.reasoning}

## Overdose Information
- **Severity Risk:** ${data.overdose.severity}
- **Action to Take:** ${data.overdose.actionToTake}

**Symptoms:**
${data.overdose.symptoms.map(s => `- ${s}`).join('\n')}

## Effect Timeline
${data.detailedTimeline.map(t => `- **${t.stage}:** ${t.description}`).join('\n')}

## Body System Effects
${data.bodySystemEffects.map(effect => `
### ${effect.system} (Severity Risk: ${effect.severity}/10)
**Positive Effects:**
${effect.positiveEffects.map(e => `- ${e}`).join('\n')}

**Negative Effects:**
${effect.negativeEffects.map(e => `- ${e}`).join('\n')}

**Serious Risks:**
${effect.seriousRisks.map(e => `- ${e}`).join('\n')}

**Monitoring:** ${effect.monitoring}

**Reasoning:** ${effect.reasoning}
**Sources:** ${effect.sources.join(', ')}
`).join('\n')}

## Key Interactions
${data.interactions.map(interaction => `
### ${interaction.interactingSubstance} (${interaction.type} - ${interaction.severity})
${interaction.description}
`).join('\n')}

---
*Disclaimer: This report is generated by AI for educational purposes and should not replace professional medical advice.*
  `;

  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${data.summary.genericName.replace(/\s+/g, '_')}_Impact_Report.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
